language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository

script:
  ./gradlew build
