language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-28

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-armeabi-v7a-android-19
  - sys-img-x86-android-17
