language: android
android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-android-support
  - sys-img-armeabi-v7a-android-28

  licenses:
  - 'android-sdk-license.*'

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
