language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-26
<<<<<<< HEAD
  - android-$EMULATOR_API
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-28
=======
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
>>>>>>> de2d25b6e4b15771f7df7b22b8c51c79b1fcb575

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
