package com.example.ganks.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xforg.gank_core.entity.DaoMeiziEntity;

import com.example.ganks.greendao.DaoMeiziEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoMeiziEntityDaoConfig;

    private final DaoMeiziEntityDao daoMeiziEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoMeiziEntityDaoConfig = daoConfigMap.get(DaoMeiziEntityDao.class).clone();
        daoMeiziEntityDaoConfig.initIdentityScope(type);

        daoMeiziEntityDao = new DaoMeiziEntityDao(daoMeiziEntityDaoConfig, this);

        registerDao(DaoMeiziEntity.class, daoMeiziEntityDao);
    }
    
    public void clear() {
        daoMeiziEntityDaoConfig.clearIdentityScope();
    }

    public DaoMeiziEntityDao getDaoMeiziEntityDao() {
        return daoMeiziEntityDao;
    }

}
